### ISSUE TITLE
Ignored channels aren't counted.

### ISSUE THREAD

**Issue by NotLazy** [SexualRhinoceros/ModTools#10]
With ModTools(Not RH1-N0), the serverlog(and modlog) don't ignore ignored channels.

**Comment by arunesh90** [comment]
`automod was made to be run by Rhino. Not you. So if you want to run it, you'd better gosh darn know how to code or know how to debug your own stuff`
tl;dr. No support is being given for running the code on your own

**Comment by NotLazy** [comment]
@arunesh90 Could he not atleast update the modtools to the latest RH1-N0?

**Comment by SexualRhinoceros** [comment]
The mod tools aren't designed to be ran by a person. They code is only uploaded for reference or review.
