### ISSUE TITLE
Word filter triggered for word(s) not in the blacklist

### ISSUE THREAD

**Issue by BlackBeltPanda** [SexualRhinoceros/ModTools#12]
Had the phrase, "Ty, I'll take a look at it sometime today :smiley:" trigger the blacklist.
Here's the blacklist:

> ['fuck', 'fvck', 'fck', 'fack', 'fu_ck', 'bitch', 'b1tch', 'b_tch', 'bit_ch', 'asshole', 'a_hole', 'ass_hole', 'cunt', 'cvnt', 'nigger', 'nigga', 'nigguh', 'niggah', 'faggot', 'fagot', 'dick', 'd1ck', 'd_ck', 'pussy', 'pvssy', 'pu_y', 'pv_y', 'tits', 'titties', 'boobies', 'shit', 'sh_t', 'sh1t']

**Comment by SexualRhinoceros** [comment]
I've said it a few times before but adding 100 variations of a word can lead to unexpected filterings. RH1 does a fuzzy search for every word added. He catches every variation of fuck, every variation of bitch, etcetera, etcetera, etcetera.

Remove all the duplicates

**Comment by BlackBeltPanda** [comment]
Ah, didn't see that information when I was setting it up.

I had the same phrase trigger the blacklist after changing the blacklist to:

> ['fuck', 'bitch', 'asshole', 'cunt', 'nigger', 'faggot', 'dick', 'pussy', 'tits', 'shit']

**Comment by BlackBeltPanda** [comment]
With the above simplified blacklist, it also failed to catch "fukin".

**Comment by BlackBeltPanda** [comment]
Update: Had another phrase trigger the blacklist, "But its fun". I think it's triggering for the word "tits".
