### ISSUE TITLE
How do i register

### ISSUE THREAD

**Issue by RealWolfieYT** [SexualRhinoceros/ModTools#16]
I am currently on a server with the bot but I need it to transfer the registration process from one person to me

**Comment by DoNotSpamPls** [comment]
Sorry, but once the registration process has started it cannot be transferred to another user.
Sorry for the inconvinience

**Comment by DoNotSpamPls** [comment]
At the moment, there is no fix for this problem, because once the registration process has started, it can't be transfered to another person.
Sorry for the inconvinience
