### ISSUE TITLE
Add info to the setup dialog and commands wiki that keyword matching is "fuzzy"

### ISSUE THREAD

**Issue by amici-ursi** [SexualRhinoceros/ModTools#18]
We set up an explicit word filter on our server, only to have users moderated for things that weren't in the filter. It took a while to diagnose because there's no mention of fuzzy matching that i could find in any of the documentation. I only found it because of https://github.com/SexualRhinoceros/ModTools/issues/12#issuecomment-219709319.

**Comment by SexualRhinoceros** [comment]
gonna be fixed in 2.0 coming soon
