### ISSUE TITLE
Allow to set role name for muting

### ISSUE THREAD

**Issue by Technical-13** [SexualRhinoceros/ModTools#19]
Since a lot of servers on Discord are gaming oriented, and `@Muted` is kind of dry s a role name, I would like to create my own role for muting, be able to name it what I want (`Time Out`, `Stockade`, `Southern Dungeon`, whatever), and tell RH1-N0 that my muted role is ___(whatever it is)___.

**Comment by SexualRhinoceros** [comment]
coming in 2.0 which is dropping soon
