### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Ev1dentFir3** [SexualRhinoceros/ModTools#2]
Can you add a feature to the bot that will monitor RSS Feeds and automatically post RSS updates to a specifically set text channel.

If you could add this it would be a great tool for gaming communities who have servers that need constantly updated, everyone would get a notification when the devs drop an update by adding that games update rss feed from steam or another source. Also good for stalking the devs of a specific game if that's what your discord if for.

Also have the option to @everyone on rss posts.

Commands could be.

!rss add [rss link] channel [#channel name] everyone 

if you don't want it to mention everyone just remove that from the end of the command.

then add a command to list all rss feeds.

!rss list

then add a command to remove an rss feed or remove all rss feeds

!rss remove ["rss feed name"]\all (use all only if you want to delete all rss feeds)

Thanks!

**Comment by SexualRhinoceros** [comment]
thats not a bad idea added it to my personal notes and will try and push it out with 2.0

**Comment by Ev1dentFir3** [comment]
Glad you like it, thanks alot man! Keep up the awesome work!

**Comment by SexualRhinoceros** [comment]
decided that its out of the scope of RH1, wont be adding

**Comment by amici-ursi** [comment]
@Ev1dentFir3, if you don't mind me interjecting, i've been using robonitori for this. https://www.reddit.com/r/discordapp/comments/47ygx9/new_discord_bot_for_reddit_and_rss_feeds/
