### ISSUE TITLE
Don't claim person deleted their own messages in log

### ISSUE THREAD

**Issue by Technical-13** [SexualRhinoceros/ModTools#20]
`[21:39:16] TRUTH| RH1-N0#6993 deleted their message: [21:39:05] ⚠ Spectra#​7794 changed their avatar`

RH1-N0#6993 didn't delete the message, I did.  It would be more appropriate for it to read:
`[21:39:16] TRUTH| RH1-N0#6993's message was deleted: [21:39:05] ⚠ Spectra#​7794 changed their avatar`

At least until information is available on who actually deleted the message.

**Comment by SexualRhinoceros** [comment]
I'll make this change but super nonissue
