### ISSUE TITLE
More of a Request :D

### ISSUE THREAD

**Issue by 4g0tt3nSou1** [SexualRhinoceros/ModTools#21]
I am looking to deploy this locally (It's not that I don't trust you, It's just I don't trust you :D)
Looking at the configs you only have userid auth not botid... 
In future, I'd love to see the ability to auth using botid's for the bot tag, and etc.

**Comment by SexualRhinoceros** [comment]
this will never be something you can deploy locally.
RH1 runs on 1k servers right now all with administrator enabled for him and is recommended by discord developers to people frequently. Can't get more trustworthy from a developer stand point.
