### ISSUE TITLE
won't play any music

### ISSUE THREAD

**Issue by jspain93** [SexualRhinoceros/ModTools#22]
i switched the server the bot was on, but for a while now it wont play any music or requests and i dont know how to fix it

**Comment by SexualRhinoceros** [comment]
a- are you serious?

**Comment by jspain93** [comment]
im very, very dumb. it can be the smallest thing and i still wont know whats wrong

**Comment by jspain93** [comment]
and i ment  the discord server is what i switched

**Comment by SunDwarf** [comment]
how do I install musicbot

**Comment by link2110** [comment]
Alright since nobody has told you @jspain93 this is ModTools, aka RH1-NO the modbot, not the musicbot. Ya know, incase you didn't see the repo name and all.

**Comment by ImthePeach** [comment]
Hey @jspain93 I'll assist you a bit, try this url instead: https://github.com/SexualRhinoceros/MusicBot/wiki
