### ISSUE TITLE
[Request] Quote

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [SexualRhinoceros/ModTools#23]
A few bots have a "Quote" feature where it creates a false quote and basically posts it in chat.
However it'd be fun to have an actual fully working quote system, where you can use a command say:
Quote Add "[2:49 PM] Inside Awakener: I'm gonna leave now. The bleach isn't gonna drink itself
[2:50 PM] PwnerTex: <3"
or Quote List <Number> <Search Term>
or Quote Remove <Number>
Really it's pretty simple, I was thinking of making it my self, but I'm incredibly lazy.
It basically just saves strings with an assigned number in a txt, and imports it into a table which is then called depending on the command and the parameters.
Oh and, The music bot is quite loved in the server, thanks for making that open source, we use it quite....
Frequently.

**Comment by Brayzure** [comment]
This doesn't sound like a relevant feature for ModTools.
