### ISSUE TITLE
Command Delay

### ISSUE THREAD

**Issue by mandm635** [SexualRhinoceros/ModTools#24]
RH1-N0 has become extremely unresponsive, the !!ping command taking about 5 min at least to pong. I noticed this issue yesterday, and am still experiencing issues. Thanks for the help -MandM635

**Comment by jaydenkieran** [comment]
Improvements have been made to RH1-N0 and this delay should be much much less now (~30 seconds).

**Comment by mandm635** [comment]
Yup seems to be fixed!
