### ISSUE TITLE
[Problem] !!dupeletters filter triggers for code blocks

### ISSUE THREAD

**Issue by Pink-Silver** [SexualRhinoceros/ModTools#26]
If a user is trying to post a code block that has spaces or tabs for indentation inside of a code block, RH1's dupe letter anti-spam triggers and deletes the message. It should ignore whitespace in blocks like this since it's valid in this case.

**Comment by SexualRhinoceros** [comment]
If I don't filter within the code blocks people will be able to abuse this. This may come in the long future as an option for people seeing this but not for a very long time
