### ISSUE TITLE
The bot listens to other bots

### ISSUE THREAD

**Issue by harbingerofme** [SexualRhinoceros/ModTools#27]
This can cause a permissions issue, especially with echo commands.

**Comment by SexualRhinoceros** [comment]
I cannot skip over bots when it comes to filtering as people can bring forth undesirable stuff from bots. its easier to have the "everything or nothing" approach though I may include very popular bots in the near future. Echo commands can be very bad as they can be abused to get around filters so I'll consider that when including certain bots
