### ISSUE TITLE
python

### ISSUE THREAD

**Issue by KDiaCoding** [SexualRhinoceros/ModTools#28]
I have python installed but it keeps saying "python is not recognised as an internal or external command, operable program or batch file." how can I fix it?

**Comment by Beefywhale** [comment]
What is the command you are using?

**Comment by xmark2** [comment]
I think you haven't add your python path to a dire

My Computer > Properties > Advanced System Settings > Environment Variables >System Variables

Please find the Path Variable and add the path of your python folder
;C:\Python27\;C:\Python27\Scripts\

please note that semicolon is the separator in the variables. after this you can open command prompt and you can type "python" and it'd work properly
