### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by thegimliboy** [SexualRhinoceros/ModTools#3]
```
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from automod import AutoMod
  File "/home/jan/Arbeitsfläche/Discord/ModTools/automod/__init__.py", line 1, in <module>
    from .bot import AutoMod
  File "/home/jan/Arbeitsfläche/Discord/ModTools/automod/bot.py", line 221
    async def on_ready(self):
            ^
SyntaxError: invalid syntax
```

I'm on linux so I use `python3 run.py` to run the server... But I get the error shown above... (I did the pip installation)

**Comment by SexualRhinoceros** [comment]
The bot is meant to be run on  python 3.5

**Comment by thegimliboy** [comment]
I use python3.5...

**Comment by SexualRhinoceros** [comment]
its throwing an error because of the keyword 'async' in front of the def. If you don't know how to code at all or can't trace code using the error reporter I suggest you just use the already running RH1-N0 bot as I don't provide support for the bot to people who just want to run it themselves.
