### ISSUE TITLE
[wiki]why still trumpet

### ISSUE THREAD

**Issue by commonsharp** [SexualRhinoceros/ModTools#5]
https://github.com/SexualRhinoceros/ModTools/wiki/Main 
I waste time :( banana please
https://github.com/SexualRhinoceros/ModTools/blob/56721d5aed3840f5358a64c9c3bbe7b6e2ebc5e9/automod/register.py#L74

**Comment by SexualRhinoceros** [comment]
the open sourced code differs from the wiki documentation. Please use RH1-N0!
