### ISSUE TITLE
Can't remove "@everyone" from blacklist

### ISSUE THREAD

**Issue by kyokoblows** [SexualRhinoceros/ModTools#6]
Someone blacklisted @everyone, and it's now removing every @everyone announcement. 

Doing !!blacklist remove "@everyone" , RH1-N0 says "No such item in blacklist : @everyone"

![w3o49](https://cloud.githubusercontent.com/assets/18198133/14190131/035f7bb6-f746-11e5-859c-0bccc4be8650.png)

Doing !!blacklist add "@everyone" , RH1-N0 states the user used the command in our modlog channel, but not in the channel we issued the command.
 
![agdsh](https://cloud.githubusercontent.com/assets/18198133/14190142/135c0aac-f746-11e5-9af5-587fbf94a4a7.png)

**Comment by khionu** [comment]
Temporarily, have the bot ignore your Announcement channel

**Comment by SexualRhinoceros** [comment]
The blacklist is in a very annoying state right now where it slugifies everything before storing it so @everyone will turn into aeveryone as @ gets turned into an a. I plan to fix this in 2.0 by having several different methods of word filtering as having one that "catches everything" is a tad bit annoying right now.
