### ISSUE TITLE
Delete commands after being sent

### ISSUE THREAD

**Issue by TheBrianiac** [SexualRhinoceros/ModTools#7]
Pretty straight-forward. I'd love an optional feature to delete the command from chat after it's sent. Sometimes the log is enough and I don't need to clog up general channels.

**Comment by Birdgeek** [comment]
This is a good idea and if this was coded in java I could mock it up and have a PR done within minutes. None the less, I support this idea!

**Comment by SexualRhinoceros** [comment]
that'll be a feature in the coming 2.0 release. For now, I added a clean command thru "!!cls" which will clean the chat of all of RH1's messages!
